name: habithon-server
services:
  api:
    image: node:latest
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - PGUSER=ladybird
      - PGHOST=db
      - PGPASSWORD=ladybird-qwerty
      - PGDATABASE=database
      - PGPORT=5432
      - SECRET_PASSWORD=${PASS}
    volumes:
      - type: bind
        source: ./api
        target: /api
    working_dir: /api
    command: bash -c "npm install && npm run start"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=ladybird
      - POSTGRES_PASSWORD=ladybird-qwerty
    volumes:
      - habithonDB:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
volumes:
  habithonDB:
